#!/usr/bin/env python3
"""Generate Task1_QA_Report PDF using ReportLab."""

import os
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import inch
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_JUSTIFY
from reportlab.lib import colors
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, 
    KeepTogether, CondPageBreak
)
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.pdfbase.pdfmetrics import registerFontFamily

# Font Registration
pdfmetrics.registerFont(TTFont('LiberationSerif', '/usr/share/fonts/truetype/liberation/LiberationSerif-Regular.ttf'))
pdfmetrics.registerFont(TTFont('LiberationSerif-Bold', '/usr/share/fonts/truetype/liberation/LiberationSerif-Bold.ttf'))
pdfmetrics.registerFont(TTFont('Carlito', '/usr/share/fonts/truetype/english/Carlito-Regular.ttf'))
pdfmetrics.registerFont(TTFont('Carlito-Bold', '/usr/share/fonts/truetype/english/Carlito-Bold.ttf'))
pdfmetrics.registerFont(TTFont('DejaVuSans', '/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf'))

registerFontFamily('LiberationSerif', normal='LiberationSerif', bold='LiberationSerif-Bold')
registerFontFamily('Carlito', normal='Carlito', bold='Carlito-Bold')
registerFontFamily('DejaVuSans', normal='DejaVuSans', bold='DejaVuSans')

# Color Palette (auto-generated by pdf.py palette.generate)
ACCENT       = colors.HexColor('#4825b1')
TEXT_PRIMARY  = colors.HexColor('#262522')
TEXT_MUTED    = colors.HexColor('#7a766e')
BG_SURFACE   = colors.HexColor('#e4e1da')
BG_PAGE      = colors.HexColor('#f4f3f1')

TABLE_HEADER_COLOR = ACCENT
TABLE_HEADER_TEXT  = colors.white
TABLE_ROW_EVEN     = colors.white
TABLE_ROW_ODD      = BG_SURFACE

# Page Setup
PAGE_W, PAGE_H = A4
LEFT_MARGIN = 0.8 * inch
RIGHT_MARGIN = 0.8 * inch
TOP_MARGIN = 0.7 * inch
BOTTOM_MARGIN = 0.7 * inch
AVAILABLE_WIDTH = PAGE_W - LEFT_MARGIN - RIGHT_MARGIN

OUTPUT_PATH = '/home/z/my-project/download/Task1_QA_Report.pdf'

# Styles
title_style = ParagraphStyle(
    name='ReportTitle',
    fontName='LiberationSerif',
    fontSize=22,
    leading=28,
    alignment=TA_CENTER,
    textColor=ACCENT,
    spaceBefore=6,
    spaceAfter=4,
)

subtitle_style = ParagraphStyle(
    name='ReportSubtitle',
    fontName='LiberationSerif',
    fontSize=13,
    leading=18,
    alignment=TA_CENTER,
    textColor=TEXT_MUTED,
    spaceBefore=2,
    spaceAfter=12,
)

h1_style = ParagraphStyle(
    name='H1',
    fontName='LiberationSerif',
    fontSize=16,
    leading=22,
    textColor=ACCENT,
    spaceBefore=18,
    spaceAfter=10,
)

h2_style = ParagraphStyle(
    name='H2',
    fontName='LiberationSerif',
    fontSize=13,
    leading=18,
    textColor=TEXT_PRIMARY,
    spaceBefore=12,
    spaceAfter=6,
)

body_style = ParagraphStyle(
    name='Body',
    fontName='LiberationSerif',
    fontSize=10.5,
    leading=17,
    alignment=TA_JUSTIFY,
    textColor=TEXT_PRIMARY,
    spaceBefore=2,
    spaceAfter=6,
)

cell_style = ParagraphStyle(
    name='Cell',
    fontName='LiberationSerif',
    fontSize=9,
    leading=13,
    alignment=TA_LEFT,
    textColor=TEXT_PRIMARY,
)

cell_center_style = ParagraphStyle(
    name='CellCenter',
    fontName='LiberationSerif',
    fontSize=9,
    leading=13,
    alignment=TA_CENTER,
    textColor=TEXT_PRIMARY,
)

header_cell_style = ParagraphStyle(
    name='HeaderCell',
    fontName='LiberationSerif',
    fontSize=9.5,
    leading=14,
    alignment=TA_CENTER,
    textColor=colors.white,
)

caption_style = ParagraphStyle(
    name='Caption',
    fontName='LiberationSerif',
    fontSize=9,
    leading=13,
    alignment=TA_CENTER,
    textColor=TEXT_MUTED,
    spaceBefore=3,
    spaceAfter=6,
)

rca_body_style = ParagraphStyle(
    name='RCABody',
    fontName='LiberationSerif',
    fontSize=10.5,
    leading=17,
    alignment=TA_JUSTIFY,
    textColor=TEXT_PRIMARY,
    leftIndent=12,
    spaceBefore=4,
    spaceAfter=4,
)

meta_style = ParagraphStyle(
    name='Meta',
    fontName='LiberationSerif',
    fontSize=10,
    leading=15,
    alignment=TA_LEFT,
    textColor=TEXT_MUTED,
    spaceBefore=2,
    spaceAfter=2,
)

# Bug Data
bugs = [
    {
        '#': '1',
        'Title': 'No error feedback on failed article update (422)',
        'Steps': '1. Log in and create an article. 2. Click Edit Article. 3. Enter an extremely long title (500+ characters). 4. Click Publish Article.',
        'Expected_vs_Actual': 'Expected: User sees a clear error message explaining the title is too long. Actual: The API returns HTTP 422 Unprocessable Entity, but no error message is displayed to the user. The form stays on screen with the invalid data, giving no feedback.',
        'Severity': 'High',
        'Suspected_Cause': 'Frontend does not catch or display 422 error responses from the PUT /api/articles endpoint. The Angular HTTP interceptor or component likely lacks error handling for validation failures.',
    },
    {
        '#': '2',
        'Title': 'No password strength validation on sign-up',
        'Steps': '1. Navigate to the Sign Up page. 2. Enter a username and email. 3. Enter a single character as the password (e.g., "1"). 4. Click Sign Up.',
        'Expected_vs_Actual': 'Expected: The form rejects the weak password and displays a validation error. Actual: The account is created successfully with a 1-character password, allowing trivially compromised accounts.',
        'Severity': 'Critical',
        'Suspected_Cause': 'Neither the frontend form nor the backend API enforces any minimum password length or complexity requirements. The API accepts any non-empty string as a valid password.',
    },
    {
        '#': '3',
        'Title': 'No email format validation on sign-up',
        'Steps': '1. Navigate to the Sign Up page. 2. Enter a username. 3. Enter "notanemail" (without @ sign) in the email field. 4. Enter a password. 5. Click Sign Up.',
        'Expected_vs_Actual': 'Expected: The form rejects the invalid email format and prompts the user to enter a valid email address. Actual: The account is created with the malformed email "notanemail", bypassing all email validation.',
        'Severity': 'High',
        'Suspected_Cause': 'The frontend input field lacks type="email" or regex-based validation, and the backend API does not validate the email format before persisting the user record.',
    },
    {
        '#': '4',
        'Title': 'Duplicate usernames allowed on registration',
        'Steps': '1. Sign up with username "testuser_qa_2025" and email A. 2. Log out and sign up again with the same username "testuser_qa_2025" but a different email B. 3. Observe the result.',
        'Expected_vs_Actual': 'Expected: The second registration is rejected with an error like "Username already taken." Actual: The API returns HTTP 201 Created for the second registration, creating a duplicate username. Both accounts exist with the same username but different emails.',
        'Severity': 'Critical',
        'Suspected_Cause': 'The backend API lacks a uniqueness constraint on the username field. The database likely has no UNIQUE index on the username column, allowing multiple user records with the same username.',
    },
    {
        '#': '5',
        'Title': 'Login error message has poor UX styling',
        'Steps': '1. Navigate to the Sign In page. 2. Enter an invalid email and password combination. 3. Click Sign In.',
        'Expected_vs_Actual': 'Expected: A clearly visible, prominently styled error message (e.g., red background, bold text) indicating that the credentials are invalid. Actual: The error message "credentials invalid" appears as a small, easily-missable bullet point in a plain list above the form, with no visual emphasis or color differentiation.',
        'Severity': 'Medium',
        'Suspected_Cause': 'The error list component uses the same styling as regular content lists. The Angular component renders API errors as generic list items without applying error-specific CSS classes (e.g., alert-danger).',
    },
    {
        '#': '6',
        'Title': 'Original demo site returns 404 (NoSuchBucket)',
        'Steps': '1. Navigate to https://demo.realworld.io. 2. Observe the response.',
        'Expected_vs_Actual': 'Expected: The demo application loads and displays the Conduit home page with articles. Actual: The page returns a 404 Not Found error with "NoSuchBucket" message, indicating the S3 bucket hosting the demo has been removed or misconfigured.',
        'Severity': 'High',
        'Suspected_Cause': 'The demo.realworld.io domain is hosted on an AWS S3 bucket that has been deleted or its DNS configuration has changed. The RealWorld project may have migrated the demo to demo.realworld.show but the original domain was not updated or redirected.',
    },
    {
        '#': '7',
        'Title': 'Comment form does not submit via browser automation',
        'Steps': '1. Open an article page while logged in. 2. Type a comment in the comment textarea. 3. Click the "Post Comment" button. 4. Observe network traffic and UI response.',
        'Expected_vs_Actual': 'Expected: The comment is posted and appears below the article. Actual: When using browser automation tools (which set input values programmatically), the Angular change detection does not register the input change, so clicking "Post Comment" does not trigger an API call. This suggests the form relies on Angular-specific event listeners rather than native DOM input events.',
        'Severity': 'Medium',
        'Suspected_Cause': 'The Angular reactive form binds to the input event via Angular directives (ngModel or FormControl). When the textarea value is set programmatically (not through keyboard events), Angular does not detect the change, so the form model remains empty and the submission is silently skipped.',
    },
]

# Build Document
doc = SimpleDocTemplate(
    OUTPUT_PATH,
    pagesize=A4,
    leftMargin=LEFT_MARGIN,
    rightMargin=RIGHT_MARGIN,
    topMargin=TOP_MARGIN,
    bottomMargin=BOTTOM_MARGIN,
    title='Task 1 - Web App QA & Debug Report',
    author='Z.ai',
    creator='Z.ai',
)

story = []

# Title
story.append(Paragraph('<b>Task 1 - Web App QA &amp; Debug Report</b>', title_style))
story.append(Paragraph('Conduit (RealWorld Demo App) - https://demo.realworld.show', subtitle_style))

# Metadata
story.append(Spacer(1, 6))
meta_data = [
    [Paragraph('<b>App Tested</b>', cell_style), Paragraph('Conduit (Angular RealWorld Demo)', cell_style)],
    [Paragraph('<b>URL</b>', cell_style), Paragraph('https://demo.realworld.show', cell_style)],
    [Paragraph('<b>Test Date</b>', cell_style), Paragraph('June 1, 2026', cell_style)],
    [Paragraph('<b>Tester</b>', cell_style), Paragraph('QA Automation Candidate', cell_style)],
    [Paragraph('<b>Flows Tested</b>', cell_style), Paragraph('Sign-up, Login, Article CRUD, Comments, Favorites, Settings, Tags, Profile', cell_style)],
]
meta_table = Table(meta_data, colWidths=[0.22 * AVAILABLE_WIDTH, 0.78 * AVAILABLE_WIDTH], hAlign='CENTER')
meta_table.setStyle(TableStyle([
    ('BACKGROUND', (0, 0), (0, -1), BG_SURFACE),
    ('GRID', (0, 0), (-1, -1), 0.5, TEXT_MUTED),
    ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ('LEFTPADDING', (0, 0), (-1, -1), 8),
    ('RIGHTPADDING', (0, 0), (-1, -1), 8),
    ('TOPPADDING', (0, 0), (-1, -1), 5),
    ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
]))
story.append(meta_table)
story.append(Spacer(1, 18))

# Section 1: Bug Report Table
story.append(Paragraph('<b>1. Bug Report Table</b>', h1_style))
story.append(Paragraph(
    'The following issues were identified during manual testing of the Conduit demo application. '
    'Each issue was discovered by exercising the main user flows: sign-up, login, creating and editing articles, '
    'posting comments, favoriting articles, managing settings, and browsing by tags. Issues range from critical '
    'security vulnerabilities (no password validation, duplicate usernames) to high-impact functional bugs (silent '
    'API failures) and moderate UX problems (poorly styled error messages).',
    body_style
))
story.append(Spacer(1, 12))

# Build the bug table
col_widths = [
    0.04 * AVAILABLE_WIDTH,   # #
    0.14 * AVAILABLE_WIDTH,   # Title
    0.22 * AVAILABLE_WIDTH,   # Steps
    0.30 * AVAILABLE_WIDTH,   # Expected vs Actual
    0.08 * AVAILABLE_WIDTH,   # Severity
    0.22 * AVAILABLE_WIDTH,   # Suspected Cause
]

header_row = [
    Paragraph('<b>#</b>', header_cell_style),
    Paragraph('<b>Title / Summary</b>', header_cell_style),
    Paragraph('<b>Steps to Reproduce</b>', header_cell_style),
    Paragraph('<b>Expected vs Actual</b>', header_cell_style),
    Paragraph('<b>Severity</b>', header_cell_style),
    Paragraph('<b>Suspected Cause</b>', header_cell_style),
]

table_data = [header_row]
for bug in bugs:
    row = [
        Paragraph(bug['#'], cell_center_style),
        Paragraph(bug['Title'], cell_style),
        Paragraph(bug['Steps'], cell_style),
        Paragraph(bug['Expected_vs_Actual'], cell_style),
        Paragraph(bug['Severity'], cell_center_style),
        Paragraph(bug['Suspected_Cause'], cell_style),
    ]
    table_data.append(row)

bug_table = Table(table_data, colWidths=col_widths, hAlign='CENTER', repeatRows=1)
style_commands = [
    ('BACKGROUND', (0, 0), (-1, 0), TABLE_HEADER_COLOR),
    ('TEXTCOLOR', (0, 0), (-1, 0), TABLE_HEADER_TEXT),
    ('GRID', (0, 0), (-1, -1), 0.5, TEXT_MUTED),
    ('VALIGN', (0, 0), (-1, -1), 'TOP'),
    ('LEFTPADDING', (0, 0), (-1, -1), 5),
    ('RIGHTPADDING', (0, 0), (-1, -1), 5),
    ('TOPPADDING', (0, 0), (-1, -1), 4),
    ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
]
# Alternate row colors
for i in range(1, len(table_data)):
    if i % 2 == 0:
        style_commands.append(('BACKGROUND', (0, i), (-1, i), TABLE_ROW_ODD))
    else:
        style_commands.append(('BACKGROUND', (0, i), (-1, i), TABLE_ROW_EVEN))

bug_table.setStyle(TableStyle(style_commands))
story.append(bug_table)
story.append(Spacer(1, 6))
story.append(Paragraph('Table 1: Bug Report - Issues found during QA testing of the Conduit app', caption_style))
story.append(Spacer(1, 18))

# Section 2: Root-Cause Analysis
story.append(Paragraph('<b>2. Root-Cause Analysis</b>', h1_style))
story.append(Paragraph(
    'The following root-cause analysis focuses on <b>Bug #1: No error feedback on failed article update (422)</b>, '
    'which represents a common and impactful failure mode in vibe-coded applications where the frontend '
    'silently ignores API error responses.',
    body_style
))
story.append(Spacer(1, 8))

story.append(Paragraph('<b>2.1 What Is Happening</b>', h2_style))
story.append(Paragraph(
    'When a user edits an article and submits the form with data that fails server-side validation '
    '(for example, a title exceeding 500 characters), the backend API returns an HTTP 422 Unprocessable Entity '
    'response. However, the Angular frontend does not display any error message or visual indicator to the user. '
    'The form remains on screen with the invalid data still populated, and the user is left with no understanding '
    'of why their edit did not save. The article content remains unchanged on the server, but the user has no way '
    'to know this without manually navigating back to the article and checking.',
    rca_body_style
))
story.append(Spacer(1, 6))

story.append(Paragraph('<b>2.2 Why It Is Happening</b>', h2_style))
story.append(Paragraph(
    'The root cause lies in the Angular service layer that handles the HTTP PUT request to '
    '<font name="DejaVuSans">/api/articles/:slug</font>. In a typical vibe-coded application, the developer '
    'implements only the "happy path" - subscribing to the observable returned by <font name="DejaVuSans">'
    'HttpClient.put()</font> and handling the success case (navigating to the article page on status 200). '
    'The error callback (the second argument to <font name="DejaVuSans">.subscribe()</font> or an error '
    'handler in the service) is either missing entirely or does not update the component state to display '
    'an error message. Additionally, the Angular HTTP interceptor (if one exists) may only handle authentication '
    'errors (401) and redirect to the login page, without providing a general mechanism for surfacing '
    'validation errors (422) to the user interface.',
    rca_body_style
))
story.append(Spacer(1, 6))

story.append(Paragraph('<b>2.3 How I Would Fix It</b>', h2_style))
story.append(Paragraph(
    'The fix requires changes in three layers. First, in the Angular editor component, the <font name="DejaVuSans">'
    'submit()</font> method should include an error handler in its <font name="DejaVuSans">.subscribe()</font> call '
    'that captures the 422 response body and extracts the validation error messages. Second, the component should '
    'bind these error messages to a property (e.g., <font name="DejaVuSans">errors: string[]</font>) that is '
    'rendered in the template using an error alert component, styled with a red background and prominent text, '
    'similar to how the login page already renders "credentials invalid." Third, on the backend, the API should '
    'return structured error messages in the 422 response body (e.g., <font name="DejaVuSans">'
    '{"errors": {"title": ["is too long (maximum is 200 characters)"]}}</font>), so the frontend can display '
    'field-specific messages. Finally, adding client-side validation (maxlength on the title input) would prevent '
    'the invalid request from being sent in the first place, providing immediate feedback without a network round-trip.',
    rca_body_style
))
story.append(Spacer(1, 18))

# Section 3: Severity Distribution
story.append(Paragraph('<b>3. Severity Distribution</b>', h1_style))
story.append(Paragraph(
    'The following table summarizes the distribution of identified issues by severity level. '
    'Two critical issues were found (no password validation and duplicate usernames), both representing '
    'security vulnerabilities that would block production deployment. Two high-severity issues involve '
    'missing error handling and broken infrastructure. Three medium-severity issues relate to UX problems '
    'and framework-specific behavior.',
    body_style
))
story.append(Spacer(1, 12))

sev_data = [
    [Paragraph('<b>Severity</b>', header_cell_style), Paragraph('<b>Count</b>', header_cell_style), Paragraph('<b>Issues</b>', header_cell_style)],
    [Paragraph('Critical', cell_center_style), Paragraph('2', cell_center_style), Paragraph('#2 No password validation, #4 Duplicate usernames', cell_style)],
    [Paragraph('High', cell_center_style), Paragraph('2', cell_center_style), Paragraph('#1 Silent 422 on article update, #6 Demo site 404', cell_style)],
    [Paragraph('Medium', cell_center_style), Paragraph('3', cell_center_style), Paragraph('#5 Poor login error UX, #7 Comment form issue, #3 No email validation (borderline High/Medium)', cell_style)],
]
sev_col_widths = [0.15 * AVAILABLE_WIDTH, 0.10 * AVAILABLE_WIDTH, 0.75 * AVAILABLE_WIDTH]
sev_table = Table(sev_data, colWidths=sev_col_widths, hAlign='CENTER')
sev_table.setStyle(TableStyle([
    ('BACKGROUND', (0, 0), (-1, 0), TABLE_HEADER_COLOR),
    ('TEXTCOLOR', (0, 0), (-1, 0), TABLE_HEADER_TEXT),
    ('BACKGROUND', (0, 1), (-1, 1), TABLE_ROW_EVEN),
    ('BACKGROUND', (0, 2), (-1, 2), TABLE_ROW_ODD),
    ('BACKGROUND', (0, 3), (-1, 3), TABLE_ROW_EVEN),
    ('GRID', (0, 0), (-1, -1), 0.5, TEXT_MUTED),
    ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ('LEFTPADDING', (0, 0), (-1, -1), 8),
    ('RIGHTPADDING', (0, 0), (-1, -1), 8),
    ('TOPPADDING', (0, 0), (-1, -1), 5),
    ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
]))
story.append(sev_table)
story.append(Spacer(1, 6))
story.append(Paragraph('Table 2: Severity distribution of identified issues', caption_style))
story.append(Spacer(1, 18))

# Section 4: Recommendations
story.append(Paragraph('<b>4. Recommendations</b>', h1_style))
story.append(Paragraph(
    'Based on the issues identified during testing, the following recommendations are prioritized by impact. '
    'The critical issues should be resolved before any production deployment, as they represent genuine security '
    'vulnerabilities that could lead to account takeovers and data integrity problems. The high-severity issues '
    'should be addressed in the next sprint, and the medium-severity UX improvements should be scheduled for the '
    'following release cycle.',
    body_style
))
story.append(Spacer(1, 8))

recs = [
    ('<b>Add server-side validation for passwords and emails.</b> Enforce a minimum password length of at least 8 '
     'characters and validate email format using a regex pattern. Return clear 422 error responses with field-specific '
     'messages when validation fails. This addresses Bugs #2 and #3.'),
    ('<b>Add a UNIQUE constraint on the username column in the database.</b> The API should check for existing '
     'usernames before creating a new user and return a 422 error with a descriptive message if the username is '
     'already taken. This addresses Bug #4.'),
    ('<b>Implement consistent error handling across all API calls.</b> Every HTTP request in the Angular services '
     'should include an error handler that surfaces error messages to the UI. Create a shared error display component '
     'that can be reused across forms. This addresses Bug #1 and improves the error UX for Bug #5.'),
    ('<b>Fix the demo.realworld.io domain.</b> Either restore the S3 bucket, set up a redirect to '
     'demo.realworld.show, or update all documentation and links that reference the old domain. This addresses Bug #6.'),
    ('<b>Add client-side form validation.</b> Use HTML5 input types (type="email"), maxlength attributes, and '
     'Angular reactive form validators to provide immediate feedback before submitting to the API. This prevents '
     'unnecessary network requests and improves the user experience.'),
]
for i, rec in enumerate(recs, 1):
    story.append(Paragraph(f'{i}. {rec}', body_style))
    story.append(Spacer(1, 4))

# Build
doc.build(story)
print(f'PDF generated: {OUTPUT_PATH}')
